// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// CryptProtectData
List CryptProtectData(Rcpp::RawVector pwd, Rcpp::RawVector salt);
RcppExport SEXP _winlockr_CryptProtectData(SEXP pwdSEXP, SEXP saltSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::RawVector >::type pwd(pwdSEXP);
    Rcpp::traits::input_parameter< Rcpp::RawVector >::type salt(saltSEXP);
    rcpp_result_gen = Rcpp::wrap(CryptProtectData(pwd, salt));
    return rcpp_result_gen;
END_RCPP
}
// CryptUnprotectData
List CryptUnprotectData(Rcpp::RawVector pwd, Rcpp::RawVector salt);
RcppExport SEXP _winlockr_CryptUnprotectData(SEXP pwdSEXP, SEXP saltSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::RawVector >::type pwd(pwdSEXP);
    Rcpp::traits::input_parameter< Rcpp::RawVector >::type salt(saltSEXP);
    rcpp_result_gen = Rcpp::wrap(CryptUnprotectData(pwd, salt));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_hello_world
List rcpp_hello_world();
RcppExport SEXP _winlockr_rcpp_hello_world() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpp_hello_world());
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_winlockr_CryptProtectData", (DL_FUNC) &_winlockr_CryptProtectData, 2},
    {"_winlockr_CryptUnprotectData", (DL_FUNC) &_winlockr_CryptUnprotectData, 2},
    {"_winlockr_rcpp_hello_world", (DL_FUNC) &_winlockr_rcpp_hello_world, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_winlockr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
