// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// CryptProtectData
Rcpp::RawVector CryptProtectData(Rcpp::RawVector pwd, Rcpp::RawVector salt);
RcppExport SEXP _winlockr_CryptProtectData(SEXP pwdSEXP, SEXP saltSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::RawVector >::type pwd(pwdSEXP);
    Rcpp::traits::input_parameter< Rcpp::RawVector >::type salt(saltSEXP);
    rcpp_result_gen = Rcpp::wrap(CryptProtectData(pwd, salt));
    return rcpp_result_gen;
END_RCPP
}
// CryptUnprotectData
Rcpp::RawVector CryptUnprotectData(Rcpp::RawVector pwd, Rcpp::RawVector salt);
RcppExport SEXP _winlockr_CryptUnprotectData(SEXP pwdSEXP, SEXP saltSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::RawVector >::type pwd(pwdSEXP);
    Rcpp::traits::input_parameter< Rcpp::RawVector >::type salt(saltSEXP);
    rcpp_result_gen = Rcpp::wrap(CryptUnprotectData(pwd, salt));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_winlockr_CryptProtectData", (DL_FUNC) &_winlockr_CryptProtectData, 2},
    {"_winlockr_CryptUnprotectData", (DL_FUNC) &_winlockr_CryptUnprotectData, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_winlockr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
